name: flutter_agc_mockup
description: Mockup of the Agile Garden Club mobile app.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ">=3.1.2"
  cloud_firestore: ">=4.9.3"
  firebase_auth: ">=4.10.1"
  firebase_core: ">=2.17.0"
  firebase_ui_auth: ">=1.8.0"
  flex_color_scheme: ">=7.3.1"
  flutter_form_builder: ">=9.1.1"
  flutter_markdown: ">=0.6.18"
  flutter_native_splash: ">=2.3.3"
  flutter_riverpod: ">=2.4.2"
  form_builder_validators: ">=9.1.0"
  freezed_annotation: ">=2.4.1"
  intl: ">=0.18.1"
  json_annotation: ">=4.8.1"
  logger: ">=1.2.0"
  riverpod_annotation: ">=2.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0"
  build_runner: ">=2.3.3"
  freezed: ">=2.4.3"
  json_serializable: ">=6.7.1"
  riverpod_generator: ">=2.3.3"
  riverpod_lint: ">=2.3.0"
  custom_lint: ">=0.5.3"

flutter_native_splash:
  image: assets/images/vegetables.png
  color: "#b86814"

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: false
  assets:
    - assets/images/
    - assets/initialData/
